#!/bin/sh
#
# @name KNR prototype vtol tiltrotor
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Rafał Lesiak
#

. ${R}etc/init.d/rc.mc_defaults

# motor defines
param set-default CA_ROTOR_COUNT 4
# front right motor
param set-default CA_ROTOR0_PX 0.412
param set-default CA_ROTOR0_PY 0.4
param set-default CA_ROTOR0_PZ 0.165
param set-default CA_ROTOR0_KM 0.05 #ccw
# back left motor
param set-default CA_ROTOR1_PX -0.788
param set-default CA_ROTOR1_PY -0.4
param set-default CA_ROTOR1_PZ -0.235
param set-default CA_ROTOR1_KM 0.05
# front left motor
param set-default CA_ROTOR2_PX 0.412
param set-default CA_ROTOR2_PY -0.4
param set-default CA_ROTOR2_PZ 0.165
param set-default CA_ROTOR2_KM -0.05 #cw
# back right motor
param set-default CA_ROTOR3_PX -0.788
param set-default CA_ROTOR3_PY 0.4
param set-default CA_ROTOR3_PZ -0.235
param set-default CA_ROTOR3_KM -0.05 #cw
